name = "Optimize"
uuid = "814553bc-2060-4325-8690-3b9cbf11db21"
version = "1.0.0-DEV"
authors = ["Zejian Zhuang zejian.zhuang@uv.es"]

[deps]
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"

[compat]
FastGaussQuadrature = "1.1.0"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
